//! Golden tests: the Rust port must reproduce the legacy TypeScript sim
//! exactly. Fixtures are generated by legacy/scripts/dump-goldens.mjs from
//! the ORIGINAL ShotAnte code — see that script for the recording procedure.

use zz_core::map::generate_arena;
use zz_core::movement::step_body;
use zz_core::rng::Mulberry32;
use zz_core::types::{Body, PlayerInput};

#[test]
fn rng_matches_legacy_ts_bit_for_bit() {
    let raw = include_str!("fixtures/rng_golden.json");
    let v: serde_json::Value = serde_json::from_str(raw).expect("fixture parses");
    let seed = v["seed"].as_str().expect("seed");
    let floats = v["floats"].as_array().expect("floats");
    assert_eq!(floats.len(), 1000);

    let mut rng = Mulberry32::from_seed(seed);
    for (i, f) in floats.iter().enumerate() {
        let expect = f.as_f64().expect("float");
        let got = rng.next();
        // Bit-exact: mulberry32 is pure u32 arithmetic + one exact division.
        assert!(
            got == expect,
            "float #{i} diverged: rust={got:?} ts={expect:?}"
        );
    }
}

#[test]
fn mapgen_matches_legacy_ts() {
    let raw = include_str!("fixtures/mapgen_golden.json");
    let v: serde_json::Value = serde_json::from_str(raw).expect("fixture parses");
    let arenas = v["arenas"].as_object().expect("arenas");

    for seed in ["zz-a", "zz-b", "zz-c"] {
        let expect = &arenas[seed];
        let got = generate_arena(seed);

        assert_eq!(got.seed, seed);

        let e_walls = expect["walls"].as_array().expect("walls");
        assert_eq!(got.walls.len(), e_walls.len(), "seed {seed}: wall count");
        for (i, (gw, ew)) in got.walls.iter().zip(e_walls.iter()).enumerate() {
            for (field, g, e) in [
                ("x0", gw.x0, ew["x0"].as_f64().unwrap()),
                ("x1", gw.x1, ew["x1"].as_f64().unwrap()),
                ("y0", gw.y0, ew["y0"].as_f64().unwrap()),
                ("y1", gw.y1, ew["y1"].as_f64().unwrap()),
                ("z0", gw.z0, ew["z0"].as_f64().unwrap()),
                ("z1", gw.z1, ew["z1"].as_f64().unwrap()),
            ] {
                assert!(
                    g == e,
                    "seed {seed} wall#{i}.{field}: rust={g:?} ts={e:?} bits={:x}/{:x}",
                    g.to_bits(),
                    e.to_bits()
                );
            }
        }

        let e_spawns = expect["spawns"].as_array().expect("spawns");
        assert_eq!(got.spawns.len(), e_spawns.len(), "seed {seed}: spawn count");
        for (i, (gs, es)) in got.spawns.iter().zip(e_spawns.iter()).enumerate() {
            assert!(gs.x == es["x"].as_f64().unwrap(), "seed {seed} spawn#{i}.x");
            assert!(gs.z == es["z"].as_f64().unwrap(), "seed {seed} spawn#{i}.z");
            assert!(
                gs.yaw == es["yaw"].as_f64().unwrap(),
                "seed {seed} spawn#{i}.yaw rust={:?} ts={:?}",
                gs.yaw,
                es["yaw"].as_f64().unwrap()
            );
        }

        let e_pickups = expect["pickups"].as_array().expect("pickups");
        assert_eq!(
            got.pickups.len(),
            e_pickups.len(),
            "seed {seed}: pickup count"
        );
        for (i, (gp, ep)) in got.pickups.iter().zip(e_pickups.iter()).enumerate() {
            assert!(
                gp.x == ep["x"].as_f64().unwrap(),
                "seed {seed} pickup#{i}.x rust={:?} ts={:?}",
                gp.x,
                ep["x"].as_f64().unwrap()
            );
            assert!(
                gp.z == ep["z"].as_f64().unwrap(),
                "seed {seed} pickup#{i}.z rust={:?} ts={:?}",
                gp.z,
                ep["z"].as_f64().unwrap()
            );
        }

        assert_eq!(
            got.accent as u64,
            expect["accent"].as_u64().unwrap(),
            "seed {seed}: accent"
        );

        let e_barrels = expect["barrels"].as_array().expect("barrels");
        assert_eq!(
            got.barrels.len(),
            e_barrels.len(),
            "seed {seed}: barrel count"
        );
        for (i, (gb, eb)) in got.barrels.iter().zip(e_barrels.iter()).enumerate() {
            assert!(
                gb.x == eb["x"].as_f64().unwrap(),
                "seed {seed} barrel#{i}.x"
            );
            assert!(
                gb.z == eb["z"].as_f64().unwrap(),
                "seed {seed} barrel#{i}.z"
            );
            assert_eq!(
                gb.wall_index as u64,
                eb["wallIndex"].as_u64().unwrap(),
                "seed {seed} barrel#{i}.wallIndex"
            );
        }
    }
}

#[test]
fn movement_matches_legacy_ts() {
    let raw = include_str!("fixtures/movement_golden.json");
    let v: serde_json::Value = serde_json::from_str(raw).expect("fixture parses");

    let map_seed = v["mapSeed"].as_str().expect("mapSeed");
    let arena_half = v["arenaHalf"].as_f64().unwrap() as f32;
    let player_speed = v["playerSpeed"].as_f64().unwrap() as f32;
    let dt = v["dt"].as_f64().unwrap() as f32;
    let start = &v["start"];
    let steps = v["steps"].as_array().expect("steps");
    assert_eq!(steps.len(), 300);

    let arena = generate_arena(map_seed);
    let walls = arena.to_f32_walls();

    let mut body = Body {
        x: start["x"].as_f64().unwrap() as f32,
        y: start["y"].as_f64().unwrap() as f32,
        z: start["z"].as_f64().unwrap() as f32,
        vy: start["vy"].as_f64().unwrap() as f32,
        on_ground: start["onGround"].as_bool().unwrap(),
    };

    // Position stays well inside 1e-4 (typical max ~2e-5). Jump landings can
    // lag one tick: f32 free-fall leaves y ≈ 1e-7 above ground while TS f64
    // snaps to y=0/on_ground, so vy and on_ground differ for that single frame.
    const POS_TOL: f32 = 1e-4;
    const VY_TOL: f32 = 1e-4;
    let mut max_pos_err = 0.0f32;
    let mut max_vy_err = 0.0f32;
    let mut landing_lag_frames = 0u32;

    for (i, row) in steps.iter().enumerate() {
        let row = row.as_array().expect("step row");
        let input = PlayerInput {
            seq: i as u32,
            forward: (i % 97) < 60,
            backward: (i % 89) > 70,
            left: (i % 53) < 20,
            right: (i % 71) > 50,
            jump: (i % 45) == 0,
            fire: false,
            grenade: false,
            interact: false,
            yaw: i as f32 * 0.037,
            pitch: 0.0,
        };
        step_body(&mut body, &input, dt, player_speed, &walls, arena_half);

        let ex = row[0].as_f64().unwrap() as f32;
        let ey = row[1].as_f64().unwrap() as f32;
        let ez = row[2].as_f64().unwrap() as f32;
        let evy = row[3].as_f64().unwrap() as f32;
        let e_ground = row[4].as_u64().unwrap() == 1;

        let pos_err = (body.x - ex)
            .abs()
            .max((body.y - ey).abs())
            .max((body.z - ez).abs());
        if pos_err > max_pos_err {
            max_pos_err = pos_err;
        }
        assert!(
            pos_err <= POS_TOL,
            "step {i}: pos err {pos_err} > {POS_TOL} \
             got=({:.6},{:.6},{:.6}) exp=({:.6},{:.6},{:.6})",
            body.x,
            body.y,
            body.z,
            ex,
            ey,
            ez
        );

        // One-frame landing lag: residual f32 height above ground ≈ 1e-7.
        let landing_lag =
            !body.on_ground && e_ground && body.y > 0.0 && body.y < 1e-5 && ey.abs() < 1e-5;
        if landing_lag {
            landing_lag_frames += 1;
            let vy_err = (body.vy - evy).abs();
            if vy_err > max_vy_err {
                max_vy_err = vy_err;
            }
            continue;
        }

        let vy_err = (body.vy - evy).abs();
        if vy_err > max_vy_err {
            max_vy_err = vy_err;
        }
        assert!(
            vy_err <= VY_TOL,
            "step {i}: vy err {vy_err} > {VY_TOL} rust_vy={} ts_vy={}",
            body.vy,
            evy
        );
        assert_eq!(
            body.on_ground, e_ground,
            "step {i}: on_ground mismatch rust={} ts={}",
            body.on_ground, e_ground
        );
    }

    // Keep errors visible with --nocapture.
    eprintln!(
        "movement_matches_legacy_ts: max_pos_err={max_pos_err:.6e} \
         max_vy_err={max_vy_err:.6e} landing_lag_frames={landing_lag_frames}"
    );
    assert!(
        max_pos_err <= POS_TOL,
        "max pos err {max_pos_err} exceeded {POS_TOL}"
    );
}
