//! Golden tests: the Rust port must reproduce the legacy TypeScript sim
//! exactly. Fixtures are generated by legacy/scripts/dump-goldens.mjs from
//! the ORIGINAL ShotAnte code — see that script for the recording procedure.

use zz_core::rng::Mulberry32;

#[test]
fn rng_matches_legacy_ts_bit_for_bit() {
    let raw = include_str!("fixtures/rng_golden.json");
    let v: serde_json::Value = serde_json::from_str(raw).expect("fixture parses");
    let seed = v["seed"].as_str().expect("seed");
    let floats = v["floats"].as_array().expect("floats");
    assert_eq!(floats.len(), 1000);

    let mut rng = Mulberry32::from_seed(seed);
    for (i, f) in floats.iter().enumerate() {
        let expect = f.as_f64().expect("float");
        let got = rng.next();
        // Bit-exact: mulberry32 is pure u32 arithmetic + one exact division.
        assert!(
            got == expect,
            "float #{i} diverged: rust={got:?} ts={expect:?}"
        );
    }
}
